spring:
  application:
    name: kryxhub
  datasource:
    url: jdbc:postgresql://localhost:5432/kryxhub_db
    username: kryxhub_admin
    password: arcticocean
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 664910110649-2ovuslrloghb8f98ijjqbb5icnrekg6o.apps.googleusercontent.com
          discord:
            client-id: "1491482173214167241"
            client-secret: "6qPRXx8t95vPc-_NUua-fxvAbWy1w1QF"
            redirect-uri: "http://localhost:8080/login.html"

youtube:
  api-key: "AIzaSyCyy4pfZC2AXmHQ88HtV6Zk_FXgEZpRcQU"

vimeo:
  access-token: "6a53122fe02a07e3a90b529ae49eb33d"

twitch:
  client-id: "qufoyrl5lbs2umhdrhxv2e3sx2z4no"
  client-secret: "qd0hb6ynu3t9rri308viokoik4u2fc"

resend:
    api-key: "re_BpGemCBZ_MMNTuZHot9344oB3gpoWZatr"

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem